"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-ic_(r44hogo=_md2b&l5$@sb9vm5)i^g6lu8ny$a$7ie^m3n64"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    # Frontend
    "tailwind",
    "django_htmx",
    "theme",
    "django.contrib.staticfiles",
    # AppInstaladas
    "control.apps.ControlConfig",
    # Explicito al final para eliminar archivos antiguos
    "django_cleanup.apps.CleanupConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",  # Agregado para HTMX
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# Idioma español
LANGUAGE_CODE = "es"

# Zona horaria de Perú
TIME_ZONE = "America/Lima"

USE_I18N = True

# Habilitar formatos localizados (fechas en formato DD/MM/AAAA automáticamente)
USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Media files (uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
TAILWIND_APP_NAME = "theme"


# ============================================
# CONFIGURACIÓN DE API SUNAT
# ============================================
# Para usar una API real de SUNAT, configura tu token aquí:
# Opciones de proveedores:
#   1. apis.net.pe - Regístrate en https://apis.net.pe/
#   2. apiperu.dev - Regístrate en https://apiperu.dev/
#   3. decolecta - Regístrate en https://decolecta.com/
#
# Puedes configurar como variables de entorno:
#   export SUNAT_API_TOKEN="tu-token-aqui"
#   export SUNAT_API_PROVIDER="apis.net.pe"
# ============================================

SUNAT_API_TOKEN = os.environ.get(
    "SUNAT_API_TOKEN", "sk_12196.F7IvWizpCvtOaPm8ZFEFWGFcfnL4dizL"
)
SUNAT_API_PROVIDER = os.environ.get("SUNAT_API_PROVIDER", "decolecta")

# ============================================
# SHIP IMO CONFIGURATION
# ============================================
# La consulta de buques por IMO utiliza scraping de VesselFinder
# directamente desde Django, sin necesidad de servidor externo.
# Los datos de demostración están disponibles para:
#   - 9839133 (MSC GULSUN)
#   - 9778791 (EVER GIVEN)
#   - 9461867 (MAERSK MC-KINNEY MOLLER)
# ============================================
