# Generated by Django 5.2.7 on 2025-11-17 22:43

import control.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aprobacionaduanera',
            name='nombre_archivo_original',
        ),
        migrations.RemoveField(
            model_name='aprobacionaduanera',
            name='ruta_documento',
        ),
        migrations.RemoveField(
            model_name='aprobacionfinanciera',
            name='nombre_archivo_original',
        ),
        migrations.RemoveField(
            model_name='aprobacionfinanciera',
            name='ruta_documento',
        ),
        migrations.AddField(
            model_name='aprobacionaduanera',
            name='documento_adjunto',
            field=models.FileField(blank=True, help_text='Sube el documento aduanero en formato PDF, JPG o PNG (máx. 5MB)', null=True, upload_to='documentos/aduaneros/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), control.models.validate_document_size], verbose_name='Documento Adjunto'),
        ),
        migrations.AddField(
            model_name='aprobacionfinanciera',
            name='documento_adjunto',
            field=models.FileField(blank=True, help_text='Sube la factura en formato PDF, JPG o PNG (máx. 5MB)', null=True, upload_to='documentos/facturas/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), control.models.validate_document_size], verbose_name='Factura Adjunta'),
        ),
    ]
