# Generated by Django 5.2.7 on 2025-11-17 23:00

import control.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_remove_aprobacionaduanera_nombre_archivo_original_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprobacionpagotransitario',
            name='documento_adjunto',
            field=models.FileField(blank=True, help_text='Sube el comprobante de pago en formato PDF, JPG o PNG (máx. 5MB)', null=True, upload_to='documentos/pagos_transitarios/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), control.models.validate_document_size], verbose_name='Comprobante de Pago'),
        ),
    ]
