# Generated by Django 5.2.7 on 2025-11-27 23:57

import control.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_aprobacionpagotransitario_documento_adjunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenedor',
            name='codigo_iso',
            field=models.CharField(help_text='Código único del contenedor según norma ISO 6346 (ej: MSKU9070323)', max_length=11, unique=True, validators=[control.models.validate_iso_6346], verbose_name='Código ISO 6346'),
        ),
    ]
