# Generated by Django 5.2.7 on 2025-11-28 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_add_iso6346_validation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenedor',
            name='origen_remitente',
        ),
        migrations.AddField(
            model_name='contenedor',
            name='carrier',
            field=models.CharField(blank=True, help_text='Naviera principal que transporta el contenedor', max_length=100, null=True, verbose_name='Carrier/Naviera'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='consignatario',
            field=models.CharField(blank=True, help_text='Empresa o persona que recibe la mercancía', max_length=120, null=True, verbose_name='Consignatario/Receiver'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='destino_ciudad',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Ciudad de Destino'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='destino_pais',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='País de Destino'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='destino_puerto',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Puerto de Destino'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='fecha_eta_destino',
            field=models.DateTimeField(blank=True, help_text='Fecha estimada de llegada al destino final', null=True, verbose_name='ETA Destino Final'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='origen_ciudad',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Ciudad de Origen'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='remitente',
            field=models.CharField(blank=True, help_text='Empresa o persona que envía la mercancía', max_length=120, null=True, verbose_name='Remitente/Shipper'),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='origen_pais',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='País de Origen'),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='origen_puerto',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Puerto de Origen'),
        ),
        migrations.CreateModel(
            name='EventoContenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('GATE_OUT_EMPTY', 'Gate Out Empty - Salida vacío'), ('GATE_IN_FULL', 'Gate In Full - Ingreso cargado'), ('LOADED', 'Loaded - Cargado al buque'), ('DEPARTED', 'Departed - Zarpe del buque'), ('IN_TRANSIT', 'In Transit - En tránsito'), ('TRANSSHIPMENT', 'Transshipment - Transbordo'), ('ARRIVED', 'Arrived - Arribo del buque'), ('DISCHARGED', 'Discharged - Descargado del buque'), ('GATE_OUT_FULL', 'Gate Out Full - Salida cargado'), ('DELIVERED', 'Delivered - Entregado'), ('GATE_IN_EMPTY', 'Gate In Empty - Devolución vacío'), ('CUSTOMS_HOLD', 'Customs Hold - Retención aduanera'), ('CUSTOMS_RELEASED', 'Customs Released - Liberado aduana'), ('INSPECTION', 'Inspection - En inspección'), ('DAMAGED', 'Damaged - Daño reportado')], max_length=20, verbose_name='Tipo de Evento')),
                ('fecha_hora', models.DateTimeField(help_text='Momento en que ocurrió el evento', verbose_name='Fecha y Hora')),
                ('ubicacion_puerto', models.CharField(help_text='Puerto donde ocurrió el evento', max_length=120, verbose_name='Puerto')),
                ('ubicacion_ciudad', models.CharField(blank=True, max_length=120, null=True, verbose_name='Ciudad')),
                ('ubicacion_pais', models.CharField(max_length=60, verbose_name='País')),
                ('medio_transporte', models.CharField(choices=[('VESSEL', 'Buque'), ('TRUCK', 'Camión'), ('RAIL', 'Ferrocarril'), ('BARGE', 'Barcaza')], default='VESSEL', max_length=10, verbose_name='Medio de Transporte')),
                ('referencia_viaje', models.CharField(blank=True, help_text='Número de viaje o voyage del buque', max_length=50, null=True, verbose_name='Referencia de Viaje')),
                ('notas', models.TextField(blank=True, help_text='Observaciones adicionales del evento', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buque', models.ForeignKey(blank=True, help_text='Buque asociado al evento (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_contenedores', to='control.buque', verbose_name='Buque')),
                ('contenedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='control.contenedor', verbose_name='Contenedor')),
            ],
            options={
                'verbose_name': 'Evento de Contenedor',
                'verbose_name_plural': 'Eventos de Contenedores',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['contenedor', '-fecha_hora'], name='control_eve_contene_80c209_idx'), models.Index(fields=['tipo_evento'], name='control_eve_tipo_ev_147002_idx'), models.Index(fields=['fecha_hora'], name='control_eve_fecha_h_eb7218_idx')],
            },
        ),
    ]
