# Generated by Django 5.2.7 on 2025-11-29 17:01

import control.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_add_tracking_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='queja',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to=control.models.queja_imagen_path, verbose_name='Imagen 1'),
        ),
        migrations.AddField(
            model_name='queja',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to=control.models.queja_imagen_path, verbose_name='Imagen 2'),
        ),
        migrations.AddField(
            model_name='queja',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to=control.models.queja_imagen_path, verbose_name='Imagen 3'),
        ),
        migrations.AlterField(
            model_name='queja',
            name='email_cliente',
            field=models.EmailField(max_length=254, verbose_name='Email del Cliente'),
        ),
        migrations.AlterField(
            model_name='queja',
            name='estado',
            field=models.CharField(choices=[('SIN_ESTADO', 'Sin Estado'), ('EN_PROCESO', 'En Proceso'), ('SOLUCIONADA', 'Solucionada'), ('ARCHIVADA', 'Archivada')], default='SIN_ESTADO', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='queja',
            name='nombre_cliente',
            field=models.CharField(max_length=120, verbose_name='Nombre del Cliente'),
        ),
    ]
