# Generated by Django 5.2.7 on 2025-12-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_queja_imagen1_queja_imagen2_queja_imagen3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transitario',
            name='licencia_operador',
            field=models.CharField(blank=True, help_text='Ej: MTC-2024-00123', max_length=50, verbose_name='Licencia de Operador'),
        ),
        migrations.AlterField(
            model_name='transitario',
            name='limite_credito',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto máximo de crédito en dólares americanos', max_digits=12, verbose_name='Límite de Crédito ($)'),
        ),
        migrations.AlterField(
            model_name='transitario',
            name='tipo_servicio',
            field=models.CharField(choices=[('NVOCC', 'NVOCC'), ('FFWD', 'Freight Forwarder'), ('TRUCKING', 'Trucking'), ('INTEGRAL', 'Servicio Integral')], help_text='NVOCC: Operador sin buque | FFWD: Agente de carga | TRUCKING: Transporte terrestre | INTEGRAL: Todos los servicios', max_length=20, verbose_name='Tipo de Servicio'),
        ),
    ]
