# Generated by Django 5.2.7 on 2025-12-08 20:04

import control.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_alter_transitario_licencia_operador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenedor',
            name='numero_sello',
            field=models.CharField(help_text='Ingrese los sellos del contenedor. El sello de Naviera es obligatorio.', max_length=500, validators=[control.models.validate_sellos_format], verbose_name='Sellos del Contenedor'),
        ),
        migrations.AlterField(
            model_name='transitario',
            name='tipo_servicio',
            field=models.CharField(choices=[('NVOCC', 'NVOCC'), ('FFWD', 'Freight Forwarder'), ('TRUCKING', 'Trucking'), ('INTEGRAL', 'Servicio Integral')], help_text='NVOCC: Operador sin buque | FFWD: Agente de carga | TRUCKING: Transporte terrestre | INTEGRAL: Ofrece todos los servicios anteriores', max_length=20, verbose_name='Tipo de Servicio'),
        ),
    ]
