# Generated by Django 5.2.7 on 2025-12-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_expand_numero_sello_for_multiple_seals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenedor',
            name='bic_propietario',
            field=models.CharField(blank=True, help_text='Se extrae automáticamente del Código ISO (primeras 3 letras)', max_length=4, verbose_name='BIC Propietario'),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='tipo_tamaño',
            field=models.CharField(choices=[('22G1', "22G1 - 20' Dry Standard"), ('22G0', "22G0 - 20' Dry Standard (ventilado)"), ('22R1', "22R1 - 20' Reefer"), ('22U1', "22U1 - 20' Open Top"), ('22P1', "22P1 - 20' Flat Rack"), ('22T1', "22T1 - 20' Tank"), ('42G1', "42G1 - 40' Dry Standard"), ('42G0', "42G0 - 40' Dry Standard (ventilado)"), ('45G1', "45G1 - 40' High Cube (HC)"), ('42R1', "42R1 - 40' Reefer"), ('45R1', "45R1 - 40' Reefer High Cube"), ('42U1', "42U1 - 40' Open Top"), ('42P1', "42P1 - 40' Flat Rack"), ('L5G1', "L5G1 - 45' High Cube")], help_text='Código ISO del tipo de contenedor', max_length=10, verbose_name='Tipo/Tamaño'),
        ),
    ]
