# Generated by Django 5.2.7 on 2025-12-09 15:36

from django.db import migrations, models


def convert_ambos_to_descarga(apps, schema_editor):
    """Convertir registros con AMBOS a DESCARGA (la opción más común para puertos)"""
    Arribo = apps.get_model("control", "Arribo")
    updated = Arribo.objects.filter(tipo_operacion="AMBOS").update(
        tipo_operacion="DESCARGA"
    )
    if updated:
        print(f"  → Convertidos {updated} arribos de 'AMBOS' a 'DESCARGA'")


def revert_descarga_to_ambos(apps, schema_editor):
    """Revertir no es posible, no hacemos nada"""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("control", "0009_contenedor_tipo_tamano_choices_bic_autofill"),
    ]

    operations = [
        # Primero convertir datos existentes
        migrations.RunPython(convert_ambos_to_descarga, revert_descarga_to_ambos),
        # Luego cambiar las opciones del campo
        migrations.AlterField(
            model_name="arribo",
            name="tipo_operacion",
            field=models.CharField(
                choices=[
                    ("DESCARGA", "Descarga (Importación)"),
                    ("CARGA", "Carga (Exportación)"),
                ],
                max_length=10,
                verbose_name="Tipo de Operación",
            ),
        ),
    ]
