# Generated by Django 5.2.7 on 2025-12-09 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0010_remove_ambos_tipo_operacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprobacionpagotransitario',
            name='pago_realizado',
            field=models.BooleanField(default=True, editable=False, verbose_name='Pago Realizado'),
        ),
        migrations.AlterField(
            model_name='aprobacionpagotransitario',
            name='transitario',
            field=models.ForeignKey(help_text='Se auto-completa desde el contenedor seleccionado', on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='control.transitario', verbose_name='Transitario'),
        ),
    ]
