# Generated by Django 5.2.7 on 2025-12-09 19:16

import control.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0011_pago_transitario_siempre_realizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprobacionaduanera',
            name='documento_adjunto',
            field=models.FileField(blank=True, help_text='Documento legal de aprobación. Obligatorio si está aprobado.', null=True, upload_to='documentos/aduaneros/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), control.models.validate_document_size], verbose_name='Documento Adjunto'),
        ),
        migrations.AlterField(
            model_name='aprobacionaduanera',
            name='fecha_levante',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se autoriza el retiro del contenedor. Obligatorio si está aprobado.', null=True, verbose_name='Fecha de Levante'),
        ),
        migrations.AlterField(
            model_name='aprobacionaduanera',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se realizó la revisión aduanera. No puede ser futura.', null=True, verbose_name='Fecha de Revisión'),
        ),
        migrations.AlterField(
            model_name='aprobacionaduanera',
            name='numero_despacho',
            field=models.CharField(help_text='Formato: AAA-AAAA-RR-NNNNNN o AAA-AAAA-RR-NNNNNN-SS. Ejemplo: 118-2025-10-012345', max_length=30, verbose_name='Número de Despacho (DAM/DUA)'),
        ),
        migrations.AlterField(
            model_name='aprobacionaduanera',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Obligatorio si NO está aprobado (indique el motivo del rechazo)', verbose_name='Observaciones'),
        ),
    ]
