# Generated by Django 5.2.7 on 2025-12-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0012_update_aprobacion_aduanera_help_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aprobacionfinanciera',
            name='aprobado',
        ),
        migrations.AddField(
            model_name='aprobacionfinanciera',
            name='estado_financiero',
            field=models.CharField(choices=[('PENDIENTE', '🟡 Emitida / Pendiente'), ('PAGADA', '🟢 Pagada'), ('CREDITO', '🔵 Crédito Aprobado'), ('ANULADA', '🔴 Anulada')], default='PENDIENTE', help_text='🟡 Pendiente bloquea Gate Pass | 🟢 Pagada y 🔵 Crédito liberan Gate Pass', max_length=20, verbose_name='Estado Financiero'),
        ),
        migrations.AlterField(
            model_name='aprobacionfinanciera',
            name='fecha_pago',
            field=models.DateField(blank=True, help_text="Solo disponible cuando el estado es 'Pagada'", null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AlterField(
            model_name='aprobacionfinanciera',
            name='monto_usd',
            field=models.DecimalField(decimal_places=2, help_text='Monto total en dólares americanos (mínimo 0)', max_digits=12, verbose_name='Monto (USD)'),
        ),
        migrations.AlterField(
            model_name='aprobacionfinanciera',
            name='numero_factura',
            field=models.CharField(help_text='Formato factura electrónica: F001-12345678 o B001-12345678', max_length=30, unique=True, verbose_name='Número de Factura'),
        ),
        migrations.AlterField(
            model_name='aprobacionfinanciera',
            name='servicios_facturados',
            field=models.JSONField(default=list, help_text='Seleccione los servicios incluidos en la factura', verbose_name='Servicios Facturados'),
        ),
    ]
