# Generated by Django 5.2.7 on 2025-12-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0013_update_aprobacion_financiera'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='bloqueado_por_evento',
            field=models.BooleanField(default=False, help_text='Se activa automáticamente por eventos como Customs Hold, Damaged o Inspection', verbose_name='Bloqueado por Evento'),
        ),
    ]
