# Generated by Django 5.2.7 on 2025-12-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0014_add_bloqueado_por_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventocontenedor',
            name='tipo_evento',
            field=models.CharField(choices=[('GATE_OUT_EMPTY', '1. Gate Out Empty - Salida vacío (retiro)'), ('GATE_IN_FULL', '2. Gate In Full - Ingreso cargado'), ('LOADED', '3. Loaded - Cargado al buque'), ('DEPARTED', '4. Departed - Zarpe del buque'), ('IN_TRANSIT', '5. In Transit - En tránsito'), ('TRANSSHIPMENT', '6. Transshipment - Transbordo'), ('ARRIVED', '7. Arrived - Arribo del buque'), ('DISCHARGED', '8. Discharged - Descargado del buque'), ('GATE_OUT_FULL', '9. Gate Out Full - Salida cargado'), ('DELIVERED', '10. Delivered - Entregado al cliente'), ('GATE_IN_EMPTY', '11. Gate In Empty - Devolución vacío'), ('CUSTOMS_HOLD', '⚠️ Customs Hold - Retención aduanera'), ('CUSTOMS_RELEASED', '✅ Customs Released - Liberado aduana'), ('INSPECTION', '🔍 Inspection - En inspección'), ('DAMAGED', '❌ Damaged - Daño reportado')], max_length=20, verbose_name='Tipo de Evento'),
        ),
    ]
