# Generated by Django 5.2.7 on 2025-12-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0015_update_evento_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventocontenedor',
            name='ubicacion_ciudad',
            field=models.CharField(blank=True, help_text='Ciudad (no aplica para eventos en tránsito marítimo)', max_length=120, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='eventocontenedor',
            name='ubicacion_puerto',
            field=models.CharField(help_text='Puerto, terminal, almacén o dirección del evento', max_length=120, verbose_name='Lugar'),
        ),
    ]
