# Generated by Django 5.2.7 on 2025-12-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0016_alter_eventocontenedor_ubicacion_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventocontenedor',
            name='ubicacion_pais',
            field=models.CharField(blank=True, help_text="Se auto-rellena con 'Aguas Internacionales' para eventos en tránsito", max_length=60, verbose_name='País'),
        ),
    ]
